improve validaitons on cpf
convenia/vue-convenia-validator pull request #27
Opened 2020-03-16 21:13 UTC by viniazvd

if (value === '11111111111') return false
if (value === '99999999999') return false

2020-03-17 17:19 UTC, casimiroarruda requested changes
O comportamento é para CPFs com todos os números repetidos, conforme explicado no postmortem segunda e não somente 111.111.111-11 e 999.999.999-99

2020-03-17 17:52 UTC, viniazvd commented
@duodraco pronto!

2020-03-17 18:01 UTC, casimiroarruda approved these changes

2020-03-19 17:24 UTC, guibarscevicius approved these changes

2020-03-19 18:53 UTC, merged